trigger: none
pool: Ashu-pool

variables:
  Work_Dir: '$(System.DefaultWorkingDirectory)/environments/dev'


stages:
- stage: Scan_and_Lint
  jobs: 
  - job: Tfsec_and_linting
    
    steps:
    - task: PowerShell@2
      displayName: Tflint_scanning
      continueOnError: true
      inputs:
        targetType: 'inline'
        script: |
          cd $(Work_Dir)
          tflint --init
          tflint
    - task: tfsec@1
      inputs:
        version: 'v1.26.0'
        dir: '$(System.DefaultWorkingDirectory)/environments/dev'

  
    - task: NodeTool@0
      displayName: Install Node.js
      inputs:
                versionSpec: '18.x'

    - task: PowerShell@2
      displayName: RetireJS_scanning
      continueOnError: true
      inputs:
            targetType: 'inline'
            script: |
              npm install -g retire
              retire --path "$(System.DefaultWorkingDirectory)/environments/dev" --verbose

- stage: Sonarqube_Scanning
  dependsOn: Scan_and_Lint
  jobs:
  - job: Sonar_Scan
    steps:           
    - task: SonarQubePrepare@8
      inputs:
        SonarQube: 'Sonar-infra'
        scannerMode: 'cli'
        configMode: 'manual'
        cliProjectKey: 'TODO_INFRA_INFRA-AUTOMATION.git_da465554-ec99-4544-8f82-a80e4ca59bf6'
        cliSources: '$(System.DefaultWorkingDirectory)/environments/dev'
    
    - task: SonarQubeAnalyze@8
      inputs:
        jdkversion: 'JAVA_HOME_17_X64'

    - task: SonarQubePublish@8
      inputs:
        pollingTimeoutSec: '300'

- stage: Terraform_initialize_and_Plan
  displayName: Terraform init and plan
  dependsOn:  Sonarqube_Scanning
  jobs: 
  - job: Terraform_init
    steps: 
    - task: TerraformInstaller@1
      displayName: Tool_install
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      displayName: Terraform_init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(Work_Dir)'
        backendServiceArm: 'Ashu-svc'
        backendAzureRmStorageAccountName: 'stg13example'
        backendAzureRmContainerName: 'pravin'
        backendAzureRmKey: 'terraform.tfstate'
    - task: TerraformTask@5
      displayName: Terraform_plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(Work_Dir)'
        environmentServiceNameAzureRM: 'Ashu-svc'

- stage: Cost_Management
  displayName: Infracost Cost Estimation
  dependsOn: Terraform_initialize_and_Plan
  jobs:
  - job: Infracost
    displayName: Infracost Directory Scan
    steps: 
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          cd $(System.DefaultWorkingDirectory)
          infracost breakdown --path INFRA-AUTOMATION
        

- stage: Manual_validation
  dependsOn: Cost_Management
  pool: server
  jobs:
    - job: Manual_approval
      
      steps: 
      - task: ManualValidation@1
        inputs:
          notifyUsers: 'Ashutosh.pal26@outlook.com'
          approvers: 'Ashutosh.pal26@outlook.com'

- stage: Terraform_Apply
  dependsOn: Manual_validation
  jobs: 
  - job: Terraform_Apply
    steps:
    - task: TerraformTask@5
      displayName: Terraform_init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(Work_Dir)'
        backendServiceArm: 'Ashu-svc'
        backendAzureRmStorageAccountName: 'stg13example'
        backendAzureRmContainerName: 'pravin'
        backendAzureRmKey: 'terraform.tfstate'

    - task: TerraformTask@5
      displayName: Terraform_Apply
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(Work_Dir)'
        environmentServiceNameAzureRM: 'Ashu-svc'